### ISSUE TITLE
上传图片一直失败

### ISSUE THREAD

**Issue by huanDreamer** [jianzs/obsidian-qiniu-image-uploader#1]
控制台打印：401 bad token，ak/sk 确认过没有错

**Comment by jianzs** [comment]
@huanDreamer  感谢反馈！ 我更新了一个版本，添加了一个区域的选项，你试一下。如果没有生效，麻烦重启 Obsidian 然后再尝试一下。

**Comment by jianzs** [comment]
@huanDreamer  请问，问题解决了么？
