### ISSUE TITLE
区域选择有bug

### ISSUE THREAD

**Issue by Joewt** [jianzs/obsidian-qiniu-image-uploader#2]
区域选择默认为第一个，选其他选项没用，会自动跳转到第一个

**Comment by jianzs** [comment]
好嘞，我晚点看一下，你先重启 Ob 试试

**Comment by Explore-c** [comment]
刚看到了，默认选择是华北-河北

**Comment by Explore-c** [comment]
> 好嘞，我晚点看一下，你先重启 Ob 试试


我这边也是，区域默认选择是华北-河北

**Comment by Explore-c** [comment]
> > 好嘞，我晚点看一下，你先重启 Ob 试试
> 
> 我这边也是，区域默认选择是华北-河北

新建了一个河北的也不行，上传没成功

**Comment by jianzs** [comment]
@Joewt @Explore-c  最近有些忙，不好意思，区域一直显示河北的确是个 Bug，实际上已经修改成功了，这个 bug 我修复了，麻烦更新下。

至于上传没成功，我修改了个 bucket 自己尝试了下，是可以的，麻烦提供一下控制台给的错误信息，应该是通过 `ctrl/cmd + alt/option + I` 打开，在 console 页会显示错误

**Comment by Joewt** [comment]
更新了下 现在好了
