### ISSUE TITLE
上传图片不能选择文件夹

### ISSUE THREAD

**Issue by ftmcu** [jianzs/obsidian-qiniu-image-uploader#3]
上传只能到存储的根目录,不能上传到指定的文件夹，希望可以添加对文件夹的支持。

还有一个外链域名如果我自己填了http最后生成的外链会有2个http导致图片显示不出来，这不算个问题但也是可以优化一下。

**Comment by jianzs** [comment]
@ftmcu  在 名称前缀 配置项按照路径格式设置，就可以上传到特定文件夹了。例如设置成这样，那么后续所有图片都会上传至 `subfolder` 了，并以 `ob-` 开头。

<img width="809" alt="image" src="https://github.com/jianzs/obsidian-qiniu-image-uploader/assets/20160766/7a83b71f-be4d-4c99-9742-8528aa3d9d77">

**Comment by ftmcu** [comment]
感谢,确实可以,因为以前picgo是在存储空间里设置的所以我想当然以为也是在存储空间里的。
