### ISSUE TITLE
文件名的timestamp 是否可转换为ymd hms格式

### ISSUE THREAD

**Issue by xbeta-zhang** [jianzs/obsidian-qiniu-image-uploader#5]
感谢开发这款插件。
近期用到图床，看到此插件后很高兴，显然本扩展比多数人在用的 PicGo 方案更简洁。
反馈一个小问题：文件名 `timestamp` 是否可以转换为 `yymmdd-hhmmss` 格式，毕竟后者更方便人脑读取。
如果允许用户自定义ymd hms的格式，则更佳。

**Comment by jianzs** [comment]
感谢建议，如果有时间，欢迎 PR。或者等我后面有空搞一下。

**Comment by xbeta-zhang** [comment]
非开发，无能力 Pull Request，但可以做一些 Public Relation 公关宣传，哈哈~~

**Comment by jianzs** [comment]
@xbeta-zhang  已经支持了，格式可以参考这个文档： https://github.com/date-fns/date-fns/blob/main/docs/unicodeTokens.md

**Comment by xbeta-zhang** [comment]
非常感谢，尤其是贴心给出了推荐的格式示例。
突然想到一个低频场景：如果在同一秒上传几个文件，后者会覆盖前者吗？

**Comment by jianzs** [comment]
> 非常感谢，尤其是贴心给出了推荐的格式示例。 突然想到一个低频场景：如果在同一秒上传几个文件，后者会覆盖前者吗？

@xbeta-zhang  会覆盖，可以在末尾添加 `SSS` 会生成毫秒级的文件名，就没有问题了。
